### ISSUE TITLE
Get flux helm operator to be able to pull from internal registry

### ISSUE THREAD

**Issue by aperullo** [connexta/grayskull#116]
Upon the discovery that Harbor registry has a built in helm chart museum, we can now store both our images and helm charts inside the cluster. Now we would like to allow the flux helm operator to automatically be able to pull uploaded charts from there.

Having manually done it once, this is something that we would like to automate. The manual steps follow, for reference during automation:

To get chart musuem working with flux helm operator:

1. Need to create configmap with musuem ca file. 
`kubectl -n grayskull-gitops create configmap reg-ca --from-file ca.crt`

2. Add it as `extraVolume` and `extraVolumeMounts` to the values file. 
```
extraVolumeMounts:
  - name: reg-ca-vol
    mountPath: /root/.helm/repository/registry.dev.<url>

extraVolumes: 
  - name: reg-ca-vol
    configmap:
      name: reg-ca
      defaultMode: 0755
```

3. Create a secret that contains the `repositories.yaml`. Including the url, username, and password for the registry.

repositories.yaml:
```
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- name: dev-reg  
  caFile: "/root/.helm/repository/registry.dev.<url>/ca.crt"
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  password: <PASSWORD>
  url: "https://registry.dev.<url>/chartrepo/cnxta"
  username: admin

```

`kubectl -n grayskull-gitops create secret generic dev-repo --from-file repostories.yaml`

4. Configure the repositories.yaml in the values file. 

```
configureRepositories:
  enable: true
  secretName: dev-repo

```

when making helm release objects. Use url for repository instead of alias. It will reverse-lookup the url.
